# - 파드들을 묶어서 단일 진입점(VIP)을 제공합니다.
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app.kubernetes.io/name: app
spec:
  type: ClusterIP    
  
  selector:
    app.kubernetes.io/name: app
  
  ports:
    - name: http
      port: 80           # 서비스가 노출하는 포트
      targetPort: 3000  # 파드 내부 컨테이너 포트 (Node.js 앱 포트)
      protocol: TCP
